# MinGW Toolchain File
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

# 指定编译器
set(COMPILER_PREFIX "C:/msys64/mingw64")
set(CMAKE_C_COMPILER "${COMPILER_PREFIX}/bin/gcc.exe")
set(CMAKE_CXX_COMPILER "${COMPILER_PREFIX}/bin/g++.exe")
set(CMAKE_RC_COMPILER "${COMPILER_PREFIX}/bin/windres.exe")

# 指定 make 工具
set(CMAKE_MAKE_PROGRAM "${COMPILER_PREFIX}/bin/mingw32-make.exe")

# 设置查找路径
set(CMAKE_FIND_ROOT_PATH "${COMPILER_PREFIX}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# 跳过编译器检查(临时解决方案)
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
